image: php:8.0-fpm-alpine

stages:
    - quality

quality:
    stage: quality
    script:
        - ./vendor/bin/phpstan analyse -l 8 ./src
        - ./vendor/bin/php-cs-fixer fix
    before_script:
        - sudo apt-get update -y
        - sudo apt-get -yq install libssl-dev libgeoip-dev php7.3-dev php-pear 
        - echo extension=geoip.so  | sudo tee -a /etc/php/7.3/cli/conf.d/geoip.ini
        - echo "memory_limit=4096M" | sudo tee -a /etc/php/7.3/cli/conf.d/ci.ini
        - composer install --no-interaction --prefer-dist
        - cp phpunit.xml.dist phpunit.xml
        - curl -L --output local-php-security-checker $(curl -s https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4)
        - chmod +x local-php-security-checker

cache:
    paths:
        - vendor/
