version: '3.4'

services:
  php-fpm:
    build:
      context: .
      target: php-fpm
    env_file:
      - .env.local
    volumes:
      - .:/var/www

  nginx:
    build:
      context: .
      target: nginx
    env_file:
      - .env.local
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  mysql:
    image: mysql/mysql-server:8.0.23-1.1.19
    env_file:
      - .env.local
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

volumes:
  mysql-data: